<a href="https://colab.research.google.com/github/WhitneyMadafali/Water-Requirement-Prediction-for-Maize-using-KNN/blob/knn/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from seaborn import load_dataset

In [2]:
from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv


In [3]:
data = pd.read_csv('data.csv')
data

SoilMoisture  temperature  Humidity  Irrigation
0             400           30        15           0
1             200           30        32           0
2             300           21        28           0
3             500           40        22           0
4             700           23        34           0
..            ...          ...       ...         ...
496           675           25        19           1
497           210           23        17           0
498           398           25        18           0
499           678           24        18           1
500           201           21        14           0

[501 rows x 4 columns]

In [4]:
x = data.drop(['Irrigation'], axis=1)
x.head()

SoilMoisture  temperature  Humidity
0           400           30        15
1           200           30        32
2           300           21        28
3           500           40        22
4           700           23        34

In [5]:
y = data['Irrigation']
y

0      0
1      0
2      0
3      0
4      0
      ..
496    1
497    0
498    0
499    1
500    0
Name: Irrigation, Length: 501, dtype: int64

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
scaler = MinMaxScaler()

In [8]:
x = scaler.fit_transform(x)

In [9]:
x

array([[0.32183908, 0.06425703, 0.05405405],
       [0.09195402, 0.06425703, 0.28378378],
       [0.20689655, 0.02811245, 0.22972973],
       ...,
       [0.31954023, 0.04417671, 0.09459459],
       [0.64137931, 0.04016064, 0.09459459],
       [0.09310345, 0.02811245, 0.04054054]])

In [10]:
y

0      0
1      0
2      0
3      0
4      0
      ..
496    1
497    0
498    0
499    1
500    0
Name: Irrigation, Length: 501, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3,random_state=1)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
knn = KNeighborsClassifier(n_neighbors = 1)

In [15]:
knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=1)

In [16]:
ypred = knn.predict(xtest)

In [17]:
ypred

array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0])

In [18]:
from sklearn.metrics import confusion_matrix, classification_report

In [19]:
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

[[81 10]
 [10 50]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        91
           1       0.83      0.83      0.83        60

    accuracy                           0.87       151
   macro avg       0.86      0.86      0.86       151
weighted avg       0.87      0.87      0.87       151



In [20]:
error_rate = []
for i in range (1, 40):
  knn = KNeighborsClassifier(n_neighbors = i)
  knn.fit(xtrain,ytrain)
  pred_i = knn.predict(xtest)

  error_rate.append(np.mean(pred_i !=ytest))

In [21]:
knn = KNeighborsClassifier(n_neighbors =13)
knn.fit(xtrain,ytrain)
predictions = knn.predict(xtest)

In [23]:
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

[[81 10]
 [10 50]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        91
           1       0.83      0.83      0.83        60

    accuracy                           0.87       151
   macro avg       0.86      0.86      0.86       151
weighted avg       0.87      0.87      0.87       151

