<a href="https://colab.research.google.com/github/WhitneyMadafali/Water-Requirement-Prediction-for-Maize-using-KNN/blob/svm/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.preprocessing import StandardScaler

In [15]:
from google.colab import files
uploaded = files.upload()

Saving mydata.csv to mydata (2).csv


In [16]:
df = pd.read_csv('mydata.csv')

In [17]:
df.head()

temperature   humidity        ph    rainfall  Irrigation
0    22.613600  63.690706  5.749914   87.759539           0
1    26.100184  71.574769  6.931757  102.266244           0
2    23.558821  71.593514  6.657965   66.719955           0
3    19.972160  57.682729  6.596061   60.651715           0
4    18.478913  62.695039  5.970458   65.438354           0

In [18]:
#checking the total rows and columns in the dataset
df.shape

(500, 5)

In [19]:
#statistical measures of the dataset
df.describe

<bound method NDFrame.describe of      temperature   humidity        ph    rainfall  Irrigation
0      22.613600  63.690706  5.749914   87.759539           0
1      26.100184  71.574769  6.931757  102.266244           0
2      23.558821  71.593514  6.657965   66.719955           0
3      19.972160  57.682729  6.596061   60.651715           0
4      18.478913  62.695039  5.970458   65.438354           0
..           ...        ...       ...         ...         ...
495    22.107190  78.583201  6.364730   74.941366           0
496    23.038140  76.110215  6.913679   91.496975           1
497    24.547953  75.397527  7.766260   63.880799           0
498    23.738680  75.775038  7.556064   76.636692           0
499    22.318719  83.861300  7.288377   65.357470           1

[500 rows x 5 columns]>

In [20]:
#checking whether to irrigate or not
df['Irrigation'].value_counts()

0    303
1    197
Name: Irrigation, dtype: int64

In [21]:
X = df.drop(columns='Irrigation', axis=1)
Y = df['Irrigation']

In [22]:
print(X)

     temperature   humidity        ph    rainfall
0      22.613600  63.690706  5.749914   87.759539
1      26.100184  71.574769  6.931757  102.266244
2      23.558821  71.593514  6.657965   66.719955
3      19.972160  57.682729  6.596061   60.651715
4      18.478913  62.695039  5.970458   65.438354
..           ...        ...       ...         ...
495    22.107190  78.583201  6.364730   74.941366
496    23.038140  76.110215  6.913679   91.496975
497    24.547953  75.397527  7.766260   63.880799
498    23.738680  75.775038  7.556064   76.636692
499    22.318719  83.861300  7.288377   65.357470

[500 rows x 4 columns]


In [23]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
495    0
496    1
497    0
498    0
499    1
Name: Irrigation, Length: 500, dtype: int64


In [24]:
#creation of an instance
sclaer = StandardScaler()

In [25]:
#fitting of X data
scaler.fit(X)

MinMaxScaler()

In [26]:
#transforming data
standardized_data = scaler.transform(X)

In [27]:
#feeding the standardized data to the X variable
X = standardized_data

In [28]:
print(X)

[[0.4369329  0.63415831 0.34915147 0.47834963]
 [0.64610047 0.74380552 0.53294306 0.60043532]
 [0.49363873 0.7440662  0.49036493 0.30128447]
 ...
 [0.55297886 0.79697032 0.662719   0.27739067]
 [0.50442888 0.80222054 0.63003087 0.38474185]
 [0.41924241 0.91467981 0.58840215 0.28981805]]


In [29]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
495    0
496    1
497    0
498    0
499    1
Name: Irrigation, Length: 500, dtype: int64


In [46]:
#splitting the dataset into 80/20 ratio
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [47]:
print(X.shape,X_test.shape,X_train.shape)

(500, 4) (100, 4) (400, 4)


In [48]:
#model creation
classifier = svm.SVC(kernel='linear')

In [49]:
#model training using test data
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [50]:
#Accuracy score on train data
train_pred = classifier.predict(X_train)
accuracy = accuracy_score(train_pred,Y_train)

In [51]:
print("Accuracy score of train data ={}".format(accuracy))

Accuracy score of train data =0.605


In [52]:
#Accuracy score on test data
test_pred = classifier.predict(X_test)
accuracy2 = accuracy_score(test_pred,Y_test)

In [53]:
print("Accuracy score of train data ={}".format(accuracy2))

Accuracy score of train data =0.61
